[package]
name = "code_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "code_generator"
crate-type = ["cdylib"]
